[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spacetimedb-sdk = "1.0.1"
hex = "0.4"
bevy = "0.15"
leafwing-input-manager = "0.16"
futures-channel = "0.3.30"
